version: '3.0'

services:
    apache-server:
        build: .
        ports:
            - 80:80
        depends_on:
            - mariadb-server
        volumes:
            - ./crud:/var/www/html/

    mariadb-server:
        image: mariadb
        restart: always
        ports:
          - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: 123
            MARIADB_DATABASE: crud_db
        volumes:
            - mariadb_volume:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d/
volumes:
  mariadb_volume: